# golangci-lint configuration for pup
# https://golangci-lint.run/usage/configuration/

version: 2

run:
  timeout: 5m
  tests: false  # Don't lint test files

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - unused
  disable:
    - staticcheck  # Disable for now, can enable in future PR

linters-settings:
  errcheck:
    exclude-functions:
      - (io.Closer).Close
