# GoReleaser configuration for Pup
# Builds multi-platform binaries with SBOMs and signatures

version: 2

before:
  hooks:
    # Ensure go.mod is tidy
    - go mod tidy

builds:
  # Darwin builds must have CGO_ENABLED=1 so the keyring library's
  # KeychainBackend (guarded by //go:build darwin && cgo) is compiled in.
  # This build must run on a macOS CI runner.
  - id: pup-darwin
    binary: pup
    main: .
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/datadog-labs/pup/internal/version.Version={{.Version}}
      - -X github.com/datadog-labs/pup/internal/version.GitCommit={{.Commit}}
      - -X github.com/datadog-labs/pup/internal/version.BuildDate={{.Date}}

  # Linux and Windows builds use CGO_ENABLED=0 for cross-compilation.
  # These platforms do not use go-keychain and are unaffected.
  - id: pup-nix
    binary: pup
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      # Windows ARM is not commonly used
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
    ldflags:
      - -s -w
      - -X github.com/datadog-labs/pup/internal/version.Version={{.Version}}
      - -X github.com/datadog-labs/pup/internal/version.GitCommit={{.Commit}}
      - -X github.com/datadog-labs/pup/internal/version.BuildDate={{.Date}}

archives:
  - id: pup
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - docs/*

# Source archive
source:
  enabled: true
  name_template: "{{ .ProjectName }}_{{ .Version }}_source"
  format: tar.gz

# Generate checksums
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

# Generate SBOM (Software Bill of Materials)
sboms:
  - id: pup-sbom
    artifacts: archive
    documents:
      - "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}.sbom.json"

# Sign artifacts with cosign
signs:
  - cmd: cosign
    artifacts: all
    output: true
    args:
      - sign-blob
      - "--output-signature=${signature}"
      - "--output-certificate=${certificate}"
      - "${artifact}"
      - --yes

# GitHub Release
release:
  github:
    owner: datadog-labs
    name: pup
  draft: false
  prerelease: auto
  mode: append
  name_template: "Release {{ .Version }}"
  header: |
    ## Pup {{ .Version }}

    ### Installation

    Download the appropriate binary for your platform from the assets below.

    ```bash
    # Linux (x86_64)
    curl -L https://github.com/datadog-labs/pup/releases/download/{{ .Tag }}/pup_{{ .Version }}_Linux_x86_64.tar.gz | tar xz

    # macOS (Apple Silicon)
    curl -L https://github.com/datadog-labs/pup/releases/download/{{ .Tag }}/pup_{{ .Version }}_Darwin_arm64.tar.gz | tar xz

    # macOS (Intel)
    curl -L https://github.com/datadog-labs/pup/releases/download/{{ .Tag }}/pup_{{ .Version }}_Darwin_x86_64.tar.gz | tar xz
    ```

    ### Verifying Signatures

    All artifacts are signed with cosign. To verify:

    ```bash
    cosign verify-blob \
      --certificate pup_{{ .Version }}_Linux_x86_64.tar.gz.pem \
      --signature pup_{{ .Version }}_Linux_x86_64.tar.gz.sig \
      pup_{{ .Version }}_Linux_x86_64.tar.gz
    ```

  footer: |
    ### What's Changed

    See the [CHANGELOG](https://github.com/datadog-labs/pup/blob/{{ .Tag }}/CHANGELOG.md) for details.

    **Full Changelog**: https://github.com/datadog-labs/pup/compare/{{ .PreviousTag }}...{{ .Tag }}

changelog:
  use: github
  sort: asc
  abbrev: 0
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - typo
  groups:
    - title: "🚀 Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "🐛 Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "🔒 Security"
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "📚 Documentation"
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: "Other Changes"
      order: 999

# Homebrew Tap
homebrew_casks:
  - name: pup
    skip_upload: true  # We use commit-headless for signed commits
    repository:
      owner: datadog-labs
      name: homebrew-pack
    homepage: https://github.com/datadog-labs/pup
    description: "Datadog API CLI - OAuth2 + API key authentication for Datadog APIs"
    license: Apache-2.0
    binaries:
      - pup
    completions:
      bash: "completions/pup.bash"
      zsh: "completions/pup.zsh"
      fish: "completions/pup.fish"
    url:
      verified: github.com/datadog-labs/pup/releases/download

# Announce releases
announce:
  skip: false
